# Generated by Django 3.1.3 on 2022-02-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=200)),
                ('tank_value', models.FloatField(default=0)),
                ('tank_data', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=200)),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tanks')),
                ('user_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
